version = 1

[[annotations]]
path = ["**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "tui-globe authors"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["assets/**"]
precedence = "closest"
SPDX-FileCopyrightText = "https://www.naturalearthdata.com/about/terms-of-use/"
SPDX-License-Identifier = "CC0-1.0"
